module.exports = {
    65: ['./sounds/tom-analog.wav'],
    66: ['./sounds/snare-noise.wav'],
    67: ['./sounds/tom-lofi.wav'],
    68: ['./sounds/snare-pinch.wav'],
    69: ['./sounds/snare-electro.wav'],
    70: ['./sounds/tom-808.wav'],
    71: ['./sounds/snare-modular.wav'],
    72: ['./sounds/snare-electro.wav'],
    73: ['./sounds/perc-808.wav'],
    74: ['./sounds/openhat-808.wav'],
    75: ['./sounds/kick-thump.wav'],
    76: ['./sounds/kick-softy.wav'],
    77: ['./sounds/kick-slapback.wav'],
    78: ['./sounds/kick-oldschool.wav'],
    79: ['./sounds/kick-cultivator.wav'],
    80: ['./sounds/hihat-reso.wav'],
    81: ['./sounds/tom-rototom.wav'],
    82: ['./sounds/snare-brute.wav'],
    83: ['./sounds/perc-laser.wav'],
    84: ['./sounds/kick-thump.wav'],
    85: ['./sounds/clap-slapper.wav'],
    86: ['./sounds/ride-acoustic02.wav'],
    87: ['./sounds/tom-fm.wav'],
    88: ['./sounds/snare-vinyl01.wav'],
    89: ['./sounds/kick-classic.wav'],
    90: ['./sounds/kick-tron.wav']
};
